mkdir "../compiled_shaders"
mkdir "../compiled_shaders/dxil"
mkdir "../compiled_shaders/msl"
mkdir "../compiled_shaders/spirv"
shadercross "dust_last_frame.comp.hlsl" -o "../compiled_shaders/dxil/dust_last_frame.comp.dxil"
shadercross "dust_last_frame.comp.hlsl" -o "../compiled_shaders/msl/dust_last_frame.comp.msl"
shadercross "dust_last_frame.comp.hlsl" -o "../compiled_shaders/spirv/dust_last_frame.comp.spv"
shadercross "dust_second_last_frame.comp.hlsl" -o "../compiled_shaders/dxil/dust_second_last_frame.comp.dxil"
shadercross "dust_second_last_frame.comp.hlsl" -o "../compiled_shaders/msl/dust_second_last_frame.comp.msl"
shadercross "dust_second_last_frame.comp.hlsl" -o "../compiled_shaders/spirv/dust_second_last_frame.comp.spv"
shadercross "dust_last_frame_early.comp.hlsl" -o "../compiled_shaders/dxil/dust_last_frame_early.comp.dxil"
shadercross "dust_last_frame_early.comp.hlsl" -o "../compiled_shaders/msl/dust_last_frame_early.comp.msl"
shadercross "dust_last_frame_early.comp.hlsl" -o "../compiled_shaders/spirv/dust_last_frame_early.comp.spv"
shadercross "dust_second_last_frame_early.comp.hlsl" -o "../compiled_shaders/dxil/dust_second_last_frame_early.comp.dxil"
shadercross "dust_second_last_frame_early.comp.hlsl" -o "../compiled_shaders/msl/dust_second_last_frame_early.comp.msl"
shadercross "dust_second_last_frame_early.comp.hlsl" -o "../compiled_shaders/spirv/dust_second_last_frame_early.comp.spv"
shadercross "naming.comp.hlsl" -o "../compiled_shaders/dxil/naming.comp.dxil"
shadercross "naming.comp.hlsl" -o "../compiled_shaders/msl/naming.comp.msl"
shadercross "naming.comp.hlsl" -o "../compiled_shaders/spirv/naming.comp.spv"
shadercross "snowballs.comp.hlsl" -o "../compiled_shaders/dxil/snowballs.comp.dxil"
shadercross "snowballs.comp.hlsl" -o "../compiled_shaders/msl/snowballs.comp.msl"
shadercross "snowballs.comp.hlsl" -o "../compiled_shaders/spirv/snowballs.comp.spv"
